### ISSUE TITLE
Extracting coordinate data for Fiji Analysis

### ISSUE THREAD

**Issue by Sathyanesan-Lab** [Neural-Systems-at-UIO/QUINT_workflow#2]
Hello, 

Is there a way to extract pixel coordinate data of different ref atlas regions? I am doing cell counts from a particular brain regions using the QUINT workflow - and this works very well. However, I would like to perform some analysis using Fiji of the same regions from which I obtain cell counts which cannot be captured using segmentation on Ilastik.

Really appreciate your help!
Aaron

**Comment by sharoncy** [comment]
Issue answered through EBRAINS support

**Comment by Tevemadar** [comment]
Just for completeness: now there's a example calculation of coordinates on [NITRC](https://www.nitrc.org/plugins/mwiki/index.php?title=quicknii:Example_coordinate_calculation)
